//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public Nullable<decimal> DeathSumInsured { get; set; }
        public Nullable<decimal> MonthlyExpenses { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> PostCode { get; set; }
    
        public virtual Occupation Occupation { get; set; }
    }
}
